---

apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-api-config
  labels:
    app: simple-api
data:
  ASPNETCORE_URLS: http://*:8000
  ConnectionStrings__Default: Host=release-name-postgresql;Port=5432;Database=simple-api-db;Username=postgres;Password=HrEJ545cKS

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  type: {{ .Values.service.type }}
  selector:
    matchLabels:
      app: simple-api
  replicas: 3
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: maximpolianskikh/otus:lesson3
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: simple-api-config
                   
---

apiVersion: v1
kind: Service
metadata:
  name: simple-api
  labels:
    service: simple-api
spec:
  type: NodePort
  selector:
    app: simple-api
  ports:
  - name: http
    port: 8000
    targetPort: 8000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-simple-api
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /health
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: simple-api
            port:
              number: 8000
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-simple-api-extend
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$3
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /otusapp(/|$)(.*/*)(health)
        pathType: Prefix
        backend:
          service:
            name: simple-api
            port:
              number: 8000
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-simple-api
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /User
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /User
        pathType: Prefix
        backend:
          service:
            name: simple-api
            port:
              number: 8000
---

